### ISSUE TITLE
Repository in Cargo.toml is wrong

### ISSUE THREAD

**Issue by philpax** [AmbientRun/AmbientProxy#6]
`repository = "https://github.com/Ambient/AmbientProxy"`

instead of

`repository = "https://github.com/AmbientRun/AmbientProxy"`

(would fix but not sure about any CI you have)

**Comment by pierd** [comment]
Good catch, thanks. Updated: [6710371](https://github.com/AmbientRun/AmbientProxy/commit/6710371bd345c26817ef9b71a1bed2354f8bf7f4)
